# Filename: Dockerfile.jenkins-agent

FROM jenkins/inbound-agent:latest-jdk11

USER root
RUN apt-get update && \
    apt-get install -y git docker.io sudo wget curl libicu-dev && \
    usermod -aG docker jenkins
RUN wget https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh && \
    chmod +x dotnet-install.sh && \
    ./dotnet-install.sh --channel 8.0 --install-dir /usr/share/dotnet && \
    ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs
RUN npm install -g @angular/cli
USER jenkins